# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: comment.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcomment.proto\x12\x0cinternal_api\x1a\x0c\x63ommon.proto\"\x1c\n\x0e\x43ommentRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\"X\n\x14\x43ommentCreateRequest\x12\x0e\n\x06UserID\x18\x01 \x01(\x04\x12\x0f\n\x07VideoID\x18\x02 \x01(\x04\x12\x11\n\tCommentID\x18\x03 \x01(\x04\x12\x0c\n\x04Text\x18\x04 \x01(\t\"\xa5\x01\n\x0f\x43ommentResponse\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0c\n\x04Text\x18\x02 \x01(\t\x12\x0f\n\x07VideoID\x18\x03 \x01(\x04\x12\x11\n\tCommentID\x18\x04 \x01(\x04\x12\x0e\n\x06UserID\x18\x05 \x01(\x04\x12\r\n\x05Likes\x18\x06 \x01(\x04\x12\x10\n\x08\x44islikes\x18\x07 \x01(\x04\x12\x11\n\tCreatedAt\x18\x08 \x01(\x04\x12\x10\n\x08\x45\x64itedAt\x18\t \x01(\x04\"S\n\x0eGetManyRequest\x12\x0f\n\x07VideoID\x18\x01 \x01(\x04\x12\x11\n\tCommentID\x18\x02 \x01(\x04\x12\x0e\n\x06Offset\x18\x03 \x01(\r\x12\r\n\x05Limit\x18\x04 \x01(\r\"Q\n\x0fGetManyResponse\x12\r\n\x05\x43ount\x18\x01 \x01(\r\x12/\n\x08\x43omments\x18\x02 \x03(\x0b\x32\x1d.internal_api.CommentResponse2\xca\x03\n\x07\x43omment\x12\x42\n\x03Get\x12\x1c.internal_api.CommentRequest\x1a\x1d.internal_api.CommentResponse\x12\x46\n\x07GetMany\x12\x1c.internal_api.GetManyRequest\x1a\x1d.internal_api.GetManyResponse\x12J\n\x06\x43reate\x12\".internal_api.CommentCreateRequest\x1a\x1c.internal_api.StatusResponse\x12L\n\x0bGetReaction\x12\x1d.internal_api.ReactionRequest\x1a\x1e.internal_api.ReactionResponse\x12S\n\x0eUpdateReaction\x12#.internal_api.UpdateReactionRequest\x1a\x1c.internal_api.StatusResponse\x12\x44\n\x06\x44\x65lete\x12\x1c.internal_api.CommentRequest\x1a\x1c.internal_api.StatusResponseB)Z\'github.com/New-Tube/internal-api-protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comment_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/New-Tube/internal-api-protos'
  _globals['_COMMENTREQUEST']._serialized_start=45
  _globals['_COMMENTREQUEST']._serialized_end=73
  _globals['_COMMENTCREATEREQUEST']._serialized_start=75
  _globals['_COMMENTCREATEREQUEST']._serialized_end=163
  _globals['_COMMENTRESPONSE']._serialized_start=166
  _globals['_COMMENTRESPONSE']._serialized_end=331
  _globals['_GETMANYREQUEST']._serialized_start=333
  _globals['_GETMANYREQUEST']._serialized_end=416
  _globals['_GETMANYRESPONSE']._serialized_start=418
  _globals['_GETMANYRESPONSE']._serialized_end=499
  _globals['_COMMENT']._serialized_start=502
  _globals['_COMMENT']._serialized_end=960
# @@protoc_insertion_point(module_scope)
