# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test/test.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftest/test.proto\x12\x04test\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04Name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07Message\x18\x01 \x01(\t28\n\x04Test\x12\x30\n\x05Hello\x12\x12.test.HelloRequest\x1a\x13.test.HelloResponseB\x1aZ\x18internal-api-protos/testb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test.test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030internal-api-protos/test'
  _globals['_HELLOREQUEST']._serialized_start=25
  _globals['_HELLOREQUEST']._serialized_end=53
  _globals['_HELLORESPONSE']._serialized_start=55
  _globals['_HELLORESPONSE']._serialized_end=87
  _globals['_TEST']._serialized_start=89
  _globals['_TEST']._serialized_end=145
# @@protoc_insertion_point(module_scope)
