# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x0cinternal_api\x1a\x0c\x63ommon.proto\"+\n\x0bUserRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x10\n\x08Nickname\x18\x02 \x01(\t\"\x86\x01\n\x0cUserResponse\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07Surname\x18\x03 \x01(\t\x12\x10\n\x08Nickname\x18\x04 \x01(\t\x12\x14\n\x0cPasswordHash\x18\x05 \x01(\x04\x12\x11\n\tCreatedAt\x18\x06 \x01(\x04\x12\x10\n\x08\x45\x64itedAt\x18\x07 \x01(\x04\"f\n\x11UserUpdateRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0f\n\x07Surname\x18\x03 \x01(\t\x12\x10\n\x08Nickname\x18\x04 \x01(\t\x12\x14\n\x0cPasswordHash\x18\x05 \x01(\x04\"Z\n\x11UserCreateRequest\x12\x10\n\x08Nickname\x18\x01 \x01(\t\x12\x14\n\x0cPasswordHash\x18\x02 \x01(\x04\x12\x0c\n\x04Name\x18\x03 \x01(\t\x12\x0f\n\x07Surname\x18\x04 \x01(\t2\xd4\x01\n\x04User\x12<\n\x03Get\x12\x19.internal_api.UserRequest\x1a\x1a.internal_api.UserResponse\x12G\n\x06Update\x12\x1f.internal_api.UserUpdateRequest\x1a\x1c.internal_api.StatusResponse\x12\x45\n\x06\x43reate\x12\x1f.internal_api.UserCreateRequest\x1a\x1a.internal_api.UserResponseB)Z\'github.com/New-Tube/internal-api-protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/New-Tube/internal-api-protos'
  _globals['_USERREQUEST']._serialized_start=42
  _globals['_USERREQUEST']._serialized_end=85
  _globals['_USERRESPONSE']._serialized_start=88
  _globals['_USERRESPONSE']._serialized_end=222
  _globals['_USERUPDATEREQUEST']._serialized_start=224
  _globals['_USERUPDATEREQUEST']._serialized_end=326
  _globals['_USERCREATEREQUEST']._serialized_start=328
  _globals['_USERCREATEREQUEST']._serialized_end=418
  _globals['_USER']._serialized_start=421
  _globals['_USER']._serialized_end=633
# @@protoc_insertion_point(module_scope)
