# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\x12\x0cinternal_api\"*\n\x0cVideoRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0e\n\x06UserID\x18\x02 \x01(\x04*,\n\x07Privacy\x12\n\n\x06Public\x10\x00\x12\x08\n\x04Link\x10\x01\x12\x0b\n\x07Private\x10\x02\x42)Z\'github.com/New-Tube/internal-api-protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/New-Tube/internal-api-protos'
  _globals['_PRIVACY']._serialized_start=73
  _globals['_PRIVACY']._serialized_end=117
  _globals['_VIDEOREQUEST']._serialized_start=29
  _globals['_VIDEOREQUEST']._serialized_end=71
# @@protoc_insertion_point(module_scope)
