# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common_pb2 as common__pb2
import video_pb2 as video__pb2
import video_regular_pb2 as video__regular__pb2


class VideoRegularUserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInfo = channel.unary_unary(
                '/internal_api.VideoRegularUser/GetInfo',
                request_serializer=video__pb2.VideoRequest.SerializeToString,
                response_deserializer=video__regular__pb2.VideoResponse.FromString,
                )
        self.GetVideoStream = channel.unary_unary(
                '/internal_api.VideoRegularUser/GetVideoStream',
                request_serializer=video__regular__pb2.VideoStreamRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                )
        self.GetReaction = channel.unary_unary(
                '/internal_api.VideoRegularUser/GetReaction',
                request_serializer=common__pb2.ReactionRequest.SerializeToString,
                response_deserializer=common__pb2.ReactionResponse.FromString,
                )
        self.UpdateReaction = channel.unary_unary(
                '/internal_api.VideoRegularUser/UpdateReaction',
                request_serializer=common__pb2.UpdateReactionRequest.SerializeToString,
                response_deserializer=common__pb2.StatusResponse.FromString,
                )


class VideoRegularUserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVideoStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoRegularUserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=video__pb2.VideoRequest.FromString,
                    response_serializer=video__regular__pb2.VideoResponse.SerializeToString,
            ),
            'GetVideoStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVideoStream,
                    request_deserializer=video__regular__pb2.VideoStreamRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
            'GetReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReaction,
                    request_deserializer=common__pb2.ReactionRequest.FromString,
                    response_serializer=common__pb2.ReactionResponse.SerializeToString,
            ),
            'UpdateReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateReaction,
                    request_deserializer=common__pb2.UpdateReactionRequest.FromString,
                    response_serializer=common__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'internal_api.VideoRegularUser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VideoRegularUser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/internal_api.VideoRegularUser/GetInfo',
            video__pb2.VideoRequest.SerializeToString,
            video__regular__pb2.VideoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetVideoStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/internal_api.VideoRegularUser/GetVideoStream',
            video__regular__pb2.VideoStreamRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/internal_api.VideoRegularUser/GetReaction',
            common__pb2.ReactionRequest.SerializeToString,
            common__pb2.ReactionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/internal_api.VideoRegularUser/UpdateReaction',
            common__pb2.UpdateReactionRequest.SerializeToString,
            common__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
