# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_creator.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import video_pb2 as video__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_creator.proto\x12\x0cinternal_api\x1a\x0bvideo.proto\x1a\x0c\x63ommon.proto\"2\n\x13VideoCreateResponse\x12\x0f\n\x07Success\x18\x01 \x01(\x08\x12\n\n\x02ID\x18\x02 \x01(\x04\"z\n\x12VideoUpdateRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\r\n\x05Title\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x01(\t\x12&\n\x07Privacy\x18\x05 \x01(\x0e\x32\x15.internal_api.Privacy\x12\x0c\n\x04Link\x18\x06 \x01(\t2\xb8\x02\n\x10VideoCreatorUser\x12G\n\x06\x43reate\x12\x1a.internal_api.VideoRequest\x1a!.internal_api.VideoCreateResponse\x12L\n\nUpdateInfo\x12 .internal_api.VideoUpdateRequest\x1a\x1c.internal_api.StatusResponse\x12I\n\rGetUploadLink\x12\x1a.internal_api.VideoRequest\x1a\x1c.internal_api.StatusResponse\x12\x42\n\x06\x44\x65lete\x12\x1a.internal_api.VideoRequest\x1a\x1c.internal_api.StatusResponseB)Z\'github.com/New-Tube/internal-api-protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_creator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/New-Tube/internal-api-protos'
  _globals['_VIDEOCREATERESPONSE']._serialized_start=64
  _globals['_VIDEOCREATERESPONSE']._serialized_end=114
  _globals['_VIDEOUPDATEREQUEST']._serialized_start=116
  _globals['_VIDEOUPDATEREQUEST']._serialized_end=238
  _globals['_VIDEOCREATORUSER']._serialized_start=241
  _globals['_VIDEOCREATORUSER']._serialized_end=553
# @@protoc_insertion_point(module_scope)
