# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video_regular.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import video_pb2 as video__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13video_regular.proto\x12\x0cinternal_api\x1a\x0bvideo.proto\x1a\x0c\x63ommon.proto\"\xcb\x01\n\rVideoResponse\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0e\n\x06UserID\x18\x02 \x01(\x04\x12\r\n\x05Title\x18\x03 \x01(\t\x12\x13\n\x0b\x44\x65scription\x18\x04 \x01(\t\x12&\n\x07Privacy\x18\x05 \x01(\x0e\x32\x15.internal_api.Privacy\x12\x0c\n\x04Link\x18\x06 \x01(\t\x12\r\n\x05Likes\x18\x07 \x01(\x04\x12\x10\n\x08\x44islikes\x18\x08 \x01(\x04\x12\x11\n\tCreatedAt\x18\t \x01(\x04\x12\x10\n\x08\x45\x64itedAt\x18\n \x01(\x04\"A\n\x12VideoStreamRequest\x12\n\n\x02ID\x18\x01 \x01(\x04\x12\x0e\n\x06UserID\x18\x02 \x01(\x04\x12\x0f\n\x07Quality\x18\x03 \x01(\t2\xcb\x02\n\x10VideoRegularUser\x12\x42\n\x07GetInfo\x12\x1a.internal_api.VideoRequest\x1a\x1b.internal_api.VideoResponse\x12P\n\x0eGetVideoStream\x12 .internal_api.VideoStreamRequest\x1a\x1c.internal_api.StatusResponse\x12L\n\x0bGetReaction\x12\x1d.internal_api.ReactionRequest\x1a\x1e.internal_api.ReactionResponse\x12S\n\x0eUpdateReaction\x12#.internal_api.UpdateReactionRequest\x1a\x1c.internal_api.StatusResponseB)Z\'github.com/New-Tube/internal-api-protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_regular_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/New-Tube/internal-api-protos'
  _globals['_VIDEORESPONSE']._serialized_start=65
  _globals['_VIDEORESPONSE']._serialized_end=268
  _globals['_VIDEOSTREAMREQUEST']._serialized_start=270
  _globals['_VIDEOSTREAMREQUEST']._serialized_end=335
  _globals['_VIDEOREGULARUSER']._serialized_start=338
  _globals['_VIDEOREGULARUSER']._serialized_end=669
# @@protoc_insertion_point(module_scope)
